# Generated by Django 6.0.2 on 2026-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='PanCard',
        ),
    ]
