# Generated by Django 6.0.2 on 2026-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0002_panrecord_delete_pancard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panrecord',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
