# Generated by Django 6.0.2 on 2026-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0003_alter_panrecord_dob_alter_panrecord_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='dob',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='father_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
