# Generated by Django 6.0.2 on 2026-02-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0005_cinrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinRecord',
        ),
    ]
