# Generated by Django 6.0.2 on 2026-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0006_delete_cinrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_number', models.CharField(max_length=21, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('incorporation_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
