# Generated by Django 6.0.2 on 2026-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0007_cinrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinrecord',
            name='incorporation_date',
        ),
        migrations.RemoveField(
            model_name='gstrecord',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='cinrecord',
            name='registration_date',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinrecord',
            name='company_name',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='gstrecord',
            name='legal_name',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='gstrecord',
            name='trade_name',
            field=models.CharField(default='UNKNOWN', max_length=200),
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='dob',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='father_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='panrecord',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
