# Generated by Django 6.0.2 on 2026-02-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panapp', '0008_remove_cinrecord_incorporation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinrecord',
            name='cin_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cinrecord',
            name='company_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='cinrecord',
            name='registration_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
